/***
CREACION
Banco completo de preguntas (seccion 3.1): reemplaza el set demo por el banco final
(15 Matematica, 15 Verbal, 20 DISC, 30 SJT en 10 competencias x 3 escenarios).
END CREACION
***/

-- Limpieza del set demo (se reemplaza por el banco completo)
DELETE FROM respuestas_candidato WHERE pregunta_id IN (SELECT id FROM evaluacion_preguntas WHERE evaluacion_id IN (1,2,3,4));
DELETE FROM evaluacion_competencias WHERE pregunta_id IN (SELECT id FROM evaluacion_preguntas WHERE evaluacion_id IN (1,2,3,4));
DELETE FROM evaluacion_opciones WHERE pregunta_id IN (SELECT id FROM evaluacion_preguntas WHERE evaluacion_id IN (1,2,3,4));
DELETE FROM evaluacion_preguntas WHERE evaluacion_id IN (1,2,3,4);

-- ===== Matemática (15 preguntas) =====
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Si un producto cuesta S/ 80 y tiene un descuento del 25%, ¿cuál es el precio final?', 'opcion_unica', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=1), 'S/ 60', 1, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=1), 'S/ 65', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=1), 'S/ 55', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=1), 'S/ 70', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuál es el siguiente número en la secuencia: 2, 4, 8, 16, ...?', 'opcion_unica', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=2), '24', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=2), '32', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=2), '20', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=2), '18', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Un tren recorre 180 km en 3 horas. ¿Cuál es su velocidad promedio?', 'opcion_unica', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=3), '45 km/h', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=3), '60 km/h', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=3), '50 km/h', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=3), '90 km/h', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Si 3 obreros construyen un muro en 12 días, ¿cuántos días tardarán 6 obreros al mismo ritmo?', 'opcion_unica', 4);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=4), '3 días', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=4), '6 días', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=4), '12 días', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=4), '24 días', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuál es el 15% de 200?', 'opcion_unica', 5);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=5), '20', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=5), '30', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=5), '25', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=5), '35', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuál es el promedio de 8, 12, 16 y 20?', 'opcion_unica', 6);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=6), '12', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=6), '14', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=6), '16', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=6), '18', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Si x + 5 = 12, ¿cuánto vale x?', 'opcion_unica', 7);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=7), '5', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=7), '7', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=7), '8', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=7), '6', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Un artículo aumenta de S/ 50 a S/ 65. ¿Cuál es el porcentaje de aumento?', 'opcion_unica', 8);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=8), '15%', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=8), '20%', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=8), '30%', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=8), '35%', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuántos minutos hay en 2.5 horas?', 'opcion_unica', 9);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=9), '120', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=9), '150', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=9), '135', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=9), '160', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuál es el siguiente número en la secuencia: 3, 6, 12, 24, ...?', 'opcion_unica', 10);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=10), '30', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=10), '36', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=10), '48', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=10), '42', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Si 5 lápices cuestan S/ 10, ¿cuánto cuestan 8 lápices al mismo precio unitario?', 'opcion_unica', 11);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=11), 'S/ 14', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=11), 'S/ 16', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=11), 'S/ 18', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=11), 'S/ 20', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Un rectángulo mide 8 m de largo y 5 m de ancho. ¿Cuál es su área?', 'opcion_unica', 12);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=12), '13 m²', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=12), '26 m²', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=12), '40 m²', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=12), '45 m²', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Se reparten S/ 900 entre 3 personas en partes iguales. ¿Cuánto recibe cada una?', 'opcion_unica', 13);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=13), 'S/ 250', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=13), 'S/ 300', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=13), 'S/ 350', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=13), 'S/ 450', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, 'Un producto tiene un descuento del 20% y luego otro 10% adicional sobre el precio ya rebajado. Si el precio original es S/ 100, ¿cuál es el precio final?', 'opcion_unica', 14);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=14), 'S/ 70', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=14), 'S/ 72', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=14), 'S/ 75', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=14), 'S/ 80', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (2, '¿Cuál es la probabilidad de obtener cara al lanzar una moneda una vez?', 'opcion_unica', 15);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=15), '25%', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=15), '50%', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=15), '75%', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=2 AND orden=15), '100%', 0, 4);

-- ===== Verbal (15 preguntas) =====
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el sinónimo de ''diligente''', 'opcion_unica', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=1), 'Perezoso', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=1), 'Aplicado', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=1), 'Confuso', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=1), 'Distraído', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Elige la palabra que NO pertenece al grupo', 'opcion_unica', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=2), 'Manzana', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=2), 'Pera', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=2), 'Zanahoria', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=2), 'Naranja', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la analogía: Libro es a Leer como Música es a ___', 'opcion_unica', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=3), 'Ver', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=3), 'Escuchar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=3), 'Pintar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=3), 'Cocinar', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el antónimo de ''generoso''', 'opcion_unica', 4);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=4), 'Amable', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=4), 'Tacaño', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=4), 'Cordial', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=4), 'Atento', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el antónimo de ''veloz''', 'opcion_unica', 5);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=5), 'Rápido', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=5), 'Ágil', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=5), 'Lento', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=5), 'Ligero', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el sinónimo de ''arduo''', 'opcion_unica', 6);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=6), 'Fácil', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=6), 'Difícil', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=6), 'Corto', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=6), 'Simple', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la analogía: Médico es a Hospital como Profesor es a ___', 'opcion_unica', 7);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=7), 'Casa', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=7), 'Escuela', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=7), 'Parque', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=7), 'Tienda', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la oración: ''A pesar de la lluvia, decidieron ___ la excursión.''', 'opcion_unica', 8);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=8), 'cancelar', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=8), 'continuar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=8), 'olvidar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=8), 'perder', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Elige la palabra que NO pertenece al grupo', 'opcion_unica', 9);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=9), 'Alegre', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=9), 'Feliz', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=9), 'Contento', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=9), 'Triste', 1, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el sinónimo de ''meticuloso''', 'opcion_unica', 10);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=10), 'Descuidado', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=10), 'Cuidadoso', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=10), 'Rápido', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=10), 'Distraído', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la analogía: Pez es a Agua como Ave es a ___', 'opcion_unica', 11);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=11), 'Tierra', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=11), 'Aire', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=11), 'Fuego', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=11), 'Nido', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el antónimo de ''escaso''', 'opcion_unica', 12);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=12), 'Poco', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=12), 'Limitado', 0, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=12), 'Abundante', 1, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=12), 'Reducido', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la oración: ''El gerente ___ el informe antes de la reunión.''', 'opcion_unica', 13);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=13), 'ignoró', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=13), 'revisó', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=13), 'perdió', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=13), 'rompió', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Selecciona el sinónimo de ''conciso''', 'opcion_unica', 14);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=14), 'Extenso', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=14), 'Breve', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=14), 'Confuso', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=14), 'Detallado', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (3, 'Completa la analogía: Autor es a Libro como Pintor es a ___', 'opcion_unica', 15);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=15), 'Pincel', 0, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=15), 'Cuadro', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=15), 'Museo', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=3 AND orden=15), 'Color', 0, 4);

-- ===== DISC (20 preguntas ipsativas) =====
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'En el trabajo en equipo, tiendo a...', 'forzada', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=1), 'Tomar el control y dirigir las decisiones', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=1), 'Motivar y entusiasmar al equipo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=1), 'Buscar consenso y mantener la armonía', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=1), 'Analizar los datos antes de decidir', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Cuando enfrento un problema urgente...', 'forzada', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=2), 'Actúo rápido y decido de inmediato', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=2), 'Busco el apoyo y opinión de otros', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=2), 'Prefiero seguir un proceso conocido y estable', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=2), 'Reviso cuidadosamente antes de actuar', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Mi estilo de comunicación es...', 'forzada', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=3), 'Directo y orientado a resultados', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=3), 'Entusiasta y expresivo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=3), 'Paciente y conciliador', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=3), 'Preciso y basado en hechos', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Ante un cambio inesperado en el proyecto...', 'forzada', 4);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=4), 'Ajusto el plan rápidamente y tomo decisiones', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=4), 'Animo al equipo a adaptarse con actitud positiva', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=4), 'Prefiero mantener la calma y seguir paso a paso', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=4), 'Analizo el impacto antes de proceder', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'En una reunión de equipo, normalmente...', 'forzada', 5);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=5), 'Propongo la dirección a seguir', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=5), 'Genero ideas y dinamismo en la conversación', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=5), 'Escucho y busco que todos participen', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=5), 'Tomo notas detalladas y verifico datos', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Cuando recibo una crítica...', 'forzada', 6);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=6), 'La tomo como un reto a superar', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=6), 'Prefiero conversarlo abiertamente', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=6), 'La proceso con calma antes de responder', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=6), 'La analizo objetivamente para mejorar', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Frente a una meta ambiciosa...', 'forzada', 7);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=7), 'Voy directo a los resultados', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=7), 'Contagio entusiasmo al equipo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=7), 'Avanzo de forma constante y estable', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=7), 'Planifico cada paso cuidadosamente', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'En situaciones de conflicto...', 'forzada', 8);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=8), 'Confronto el tema directamente', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=8), 'Busco reconciliar con buen ánimo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=8), 'Evito la confrontación y busco armonía', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=8), 'Busco datos objetivos para resolverlo', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Mi forma de tomar decisiones es...', 'forzada', 9);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=9), 'Rápida y decidida', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=9), 'Basada en cómo afecta a las personas', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=9), 'Cautelosa y consensuada', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=9), 'Basada en análisis detallado', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Ante una tarea rutinaria...', 'forzada', 10);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=10), 'Busco maneras de hacerla más eficiente', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=10), 'Trato de hacerla más amena', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=10), 'La realizo con disciplina y constancia', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=10), 'La ejecuto siguiendo el proceso establecido', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Cuando lidero un proyecto...', 'forzada', 11);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=11), 'Marco el rumbo con firmeza', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=11), 'Motivo al equipo constantemente', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=11), 'Doy soporte y estabilidad al equipo', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=11), 'Aseguro que todo se documente bien', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'En una negociación...', 'forzada', 12);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=12), 'Busco ganar con resultados concretos', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=12), 'Persuado con entusiasmo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=12), 'Busco un acuerdo justo para ambas partes', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=12), 'Preparo argumentos basados en datos', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Frente a un error propio...', 'forzada', 13);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=13), 'Lo corrijo rápido y sigo adelante', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=13), 'Lo comento abiertamente con humor', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=13), 'Me tomo tiempo para procesarlo', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=13), 'Analizo la causa raíz para no repetirlo', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Mi ritmo de trabajo habitual es...', 'forzada', 14);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=14), 'Rápido y orientado a resultados', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=14), 'Dinámico y sociable', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=14), 'Constante y predecible', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=14), 'Metódico y detallado', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Cuando el equipo enfrenta presión...', 'forzada', 15);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=15), 'Tomo el control de la situación', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=15), 'Mantengo el ánimo del equipo', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=15), 'Ofrezco estabilidad y calma', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=15), 'Me enfoco en hacer las cosas bien, sin errores', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Prefiero un entorno de trabajo...', 'forzada', 16);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=16), 'Competitivo y desafiante', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=16), 'Sociable y dinámico', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=16), 'Predecible y colaborativo', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=16), 'Organizado y estructurado', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Al recibir instrucciones nuevas...', 'forzada', 17);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=17), 'Las ejecuto a mi manera si es más eficiente', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=17), 'Pregunto y converso sobre ellas', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=17), 'Las sigo tal como se indican', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=17), 'Las reviso en detalle antes de actuar', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Mi mayor fortaleza en equipo es...', 'forzada', 18);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=18), 'Impulsar resultados', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=18), 'Generar buen ambiente', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=18), 'Dar consistencia y apoyo', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=18), 'Garantizar calidad y precisión', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'Frente a una fecha límite ajustada...', 'forzada', 19);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=19), 'Acelero el ritmo y presiono si es necesario', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=19), 'Motivo al equipo a unirse por la meta', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=19), 'Organizo el tiempo con calma', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=19), 'Reviso que todo cumpla los estándares', 'C', 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (1, 'En una presentación importante...', 'forzada', 20);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=20), 'Voy directo a los puntos clave', 'D', 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=20), 'Busco conectar emocionalmente con la audiencia', 'I', 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=20), 'Preparo con calma y transmito seguridad', 'S', 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, etiqueta, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=1 AND orden=20), 'Preparo datos y respaldo cada afirmación', 'C', 4);

-- ===== Valores y Competencias (30 preguntas SJT) =====
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un compañero de equipo no está cumpliendo con su parte del proyecto. ¿Qué opción es más y menos efectiva?', 'sjt', 1);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=1), 'Trabajo en equipo');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=1), 'Hablar directamente con él para entender la situación y ofrecer ayuda', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=1), 'Informar al jefe inmediatamente sin hablar antes con el compañero', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=1), 'Asumir tú su parte del trabajo sin decir nada', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=1), 'Ignorar el problema y esperar que se resuelva solo', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Dos compañeros de tu equipo no se llevan bien y esto afecta el trabajo. ¿Qué opción es más y menos efectiva?', 'sjt', 2);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=2), 'Trabajo en equipo');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=2), 'Facilitar una conversación para que aclaren la situación', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=2), 'Evitar involucrarte y trabajar solo tu parte', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=2), 'Tomar partido por uno de los dos', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=2), 'Ignorar el problema aunque afecte los resultados', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'El equipo debe repartirse tareas para un proyecto grupal. ¿Qué opción es más y menos efectiva?', 'sjt', 3);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=3), 'Trabajo en equipo');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=3), 'Proponer repartir según fortalezas de cada uno y verificar acuerdo de todos', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=3), 'Tomar la parte que más te conviene sin consultar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=3), 'Esperar que otros asignen las tareas', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=3), 'Resistirte a que te asignen tareas que no elegiste', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tienes una fecha límite ajustada y notas que no vas a cumplir el plazo. ¿Qué opción es más y menos efectiva?', 'sjt', 4);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=4), 'Orientación a resultados');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=4), 'Avisas con anticipación y propones un plan para cumplir o ajustar el alcance', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=4), 'Entregas lo que tengas a tiempo aunque esté incompleto, sin avisar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=4), 'Esperas hasta el último momento para comunicar el retraso', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=4), 'No entregas nada y evitas la conversación', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Notas que el método actual del equipo para lograr una meta es ineficiente. ¿Qué opción es más y menos efectiva?', 'sjt', 5);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=5), 'Orientación a resultados');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=5), 'Proponer una mejora concreta y sustentarla con datos', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=5), 'Comentar la ineficiencia sin proponer alternativas', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=5), 'Seguir el método aunque sepas que es ineficiente', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=5), 'Dejar de esforzarte porque "no vale la pena"', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Estás cerca de cumplir tu meta mensual pero surge un imprevisto. ¿Qué opción es más y menos efectiva?', 'sjt', 6);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=6), 'Orientación a resultados');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=6), 'Ajustar tu plan y buscar alternativas para igual cumplir la meta', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=6), 'Cumplir una parte y dejar el resto para el siguiente mes sin avisar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=6), 'Darte por vencido con la meta de este mes', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=6), 'Culpar al imprevisto sin buscar soluciones', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Debes explicar un tema técnico complejo a un cliente sin conocimientos técnicos. ¿Qué opción es más y menos efectiva?', 'sjt', 7);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=7), 'Comunicación efectiva');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=7), 'Adaptas el lenguaje usando ejemplos simples y verificas que entendió', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=7), 'Usas los mismos términos técnicos que usarías con un colega', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=7), 'Envías documentación técnica extensa sin explicación adicional', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=7), 'Evitas explicar y delegas la conversación a otra persona', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Debes dar una retroalimentación negativa a un compañero. ¿Qué opción es más y menos efectiva?', 'sjt', 8);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=8), 'Comunicación efectiva');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=8), 'Darla en privado, con ejemplos concretos y de forma constructiva', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=8), 'Darla en el grupo para que "quede claro"', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=8), 'Evitar darla para no incomodar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=8), 'Darla de forma agresiva', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Recibes un correo ambiguo de un cliente. ¿Qué opción es más y menos efectiva?', 'sjt', 9);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=9), 'Comunicación efectiva');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=9), 'Preguntar directamente para aclarar antes de actuar', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=9), 'Asumir lo que crees que quiso decir', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=9), 'Ignorar el correo hasta que insistan', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=9), 'Responder con información no relacionada', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Encuentras un error de cálculo a tu favor en tu pago de comisiones. ¿Qué opción es más y menos efectiva?', 'sjt', 10);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=10), 'Integridad');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=10), 'Informar el error al área correspondiente aunque implique menos pago', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=10), 'Esperar a ver si alguien más lo nota antes de decir algo', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=10), 'Quedarte callado y aceptar el pago de más', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=10), 'Gastar el dinero antes de que puedan corregirlo', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un compañero te pide que firmes un reporte que no revisaste completamente. ¿Qué opción es más y menos efectiva?', 'sjt', 11);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=11), 'Integridad');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=11), 'Revisar el reporte a fondo antes de firmar, aunque tome más tiempo', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=11), 'Firmar confiando en que tu compañero lo hizo bien', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=11), 'Firmar sin revisar para no incomodar a tu compañero', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=11), 'Negarte a firmar sin dar ninguna explicación', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tu jefe te pide reportar cifras "más favorables" de lo real para un informe a la gerencia. ¿Qué opción es más y menos efectiva?', 'sjt', 12);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=12), 'Integridad');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=12), 'Presentar las cifras reales y explicar la situación con transparencia', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=12), 'Ajustar ligeramente las cifras solo esta vez', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=12), 'Reportar lo que pide tu jefe sin cuestionar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=12), 'Ignorar la solicitud y no entregar el informe', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Se presenta una tarea urgente fuera de tu horario habitual justo antes de un cierre importante. ¿Qué opción es más y menos efectiva?', 'sjt', 13);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=13), 'Compromiso');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=13), 'Quedarte a apoyar y avisar a tu familia/planes que llegarás tarde', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=13), 'Ayudar un rato corto y retirarte a tu hora', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=13), 'Irte a tu hora sin avisar que había una tarea pendiente', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=13), 'Ignorar el pedido y dejar que otro se encargue', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Llevas varios meses en un proyecto que se ha vuelto tedioso. ¿Qué opción es más y menos efectiva?', 'sjt', 14);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=14), 'Compromiso');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=14), 'Mantener tu nivel de esfuerzo y buscar motivación en el resultado final', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=14), 'Cumplir lo mínimo necesario hasta que termine', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=14), 'Empezar a llegar tarde y desconectarte del equipo', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=14), 'Buscar activamente moverte a otro proyecto sin terminar el actual', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tu equipo necesita que asumas una responsabilidad adicional sin aumento inmediato de sueldo. ¿Qué opción es más y menos efectiva?', 'sjt', 15);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=15), 'Compromiso');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=15), 'Aceptar y conversar abiertamente sobre expectativas a futuro', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=15), 'Aceptar pero sin mucho entusiasmo', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=15), 'Aceptar de mala gana y quejarte constantemente', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=15), 'Negarte rotundamente sin dialogar', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'La empresa implementa un nuevo sistema que reemplaza el que usabas por años. ¿Qué opción es más y menos efectiva?', 'sjt', 16);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=16), 'Adaptabilidad al cambio');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=16), 'Capacitarte activamente y ayudar a otros a adaptarse', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=16), 'Usar el nuevo sistema solo cuando es obligatorio', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=16), 'Seguir usando métodos antiguos en paralelo', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=16), 'Resistirte abiertamente al cambio', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tu rol cambia repentinamente por una reestructuración. ¿Qué opción es más y menos efectiva?', 'sjt', 17);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=17), 'Adaptabilidad al cambio');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=17), 'Buscar entender las nuevas expectativas y adaptarte rápido', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=17), 'Adaptarte pero con quejas constantes', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=17), 'Seguir actuando según tu rol anterior', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=17), 'Considerar renunciar de inmediato sin evaluar la situación', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un proyecto cambia de dirección a mitad de camino. ¿Qué opción es más y menos efectiva?', 'sjt', 18);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=18), 'Adaptabilidad al cambio');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=18), 'Ajustar tu trabajo rápidamente a la nueva dirección', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=18), 'Terminar lo que ya empezaste antes de ajustar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=18), 'Quejarte del cambio en vez de ejecutar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=18), 'Ignorar el cambio y seguir con el plan original', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Detectas un problema que no es tu responsabilidad directa, pero afecta al equipo. ¿Qué opción es más y menos efectiva?', 'sjt', 19);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=19), 'Iniciativa');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=19), 'Comunicarlo y proponer una solución aunque no sea tu área', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=19), 'Comentarlo informalmente sin dar seguimiento', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=19), 'Ignorarlo porque no es tu responsabilidad', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=19), 'Esperar que alguien más lo note', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Ves una oportunidad de mejora en un proceso que nadie ha señalado. ¿Qué opción es más y menos efectiva?', 'sjt', 20);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=20), 'Iniciativa');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=20), 'Documentar la idea y proponerla a tu jefe', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=20), 'Comentar la idea casualmente sin formalizarla', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=20), 'Guardar la idea para ti mismo', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=20), 'No hacer nada porque "no es tu trabajo"', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Terminaste tus tareas antes de tiempo. ¿Qué opción es más y menos efectiva?', 'sjt', 21);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=21), 'Iniciativa');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=21), 'Preguntar en qué más puedes ayudar', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=21), 'Esperar a que te asignen algo nuevo', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=21), 'Aprovechar para hacer tiempo personal sin avisar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=21), 'Irte antes de tu horario sin avisar', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un cliente te grita por un error que no cometiste. ¿Qué opción es más y menos efectiva?', 'sjt', 22);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=22), 'Autocontrol y manejo de la presión');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=22), 'Mantener la calma, escuchar y buscar resolver el problema', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=22), 'Disculparte rápido solo para terminar la conversación', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=22), 'Responder con el mismo tono elevado', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=22), 'Colgar o retirarte de la conversación', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tienes tres entregas urgentes al mismo tiempo. ¿Qué opción es más y menos efectiva?', 'sjt', 23);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=23), 'Autocontrol y manejo de la presión');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=23), 'Priorizar con calma y comunicar los tiempos reales', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=23), 'Trabajar apurado en las tres sin priorizar', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=23), 'Paralizarte y no avanzar en ninguna', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=23), 'Entrar en pánico y transmitir estrés al equipo', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Recibes una crítica dura frente a otros compañeros. ¿Qué opción es más y menos efectiva?', 'sjt', 24);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=24), 'Autocontrol y manejo de la presión');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=24), 'Escuchar, agradecer el feedback y conversarlo después en privado', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=24), 'Defenderte de inmediato frente a todos', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=24), 'Quedarte callado pero visiblemente molesto', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=24), 'Responder con una crítica hacia la otra persona', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un cliente solicita algo fuera del proceso establecido. ¿Qué opción es más y menos efectiva?', 'sjt', 25);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=25), 'Orientación al cliente');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=25), 'Buscar una solución dentro de lo posible y explicar las limitaciones', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=25), 'Decirle que no se puede sin explorar alternativas', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=25), 'Prometer algo que no puedes cumplir', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=25), 'Ignorar la solicitud', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Un cliente está insatisfecho con un servicio ya entregado. ¿Qué opción es más y menos efectiva?', 'sjt', 26);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=26), 'Orientación al cliente');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=26), 'Escuchar su queja, disculparte y buscar una solución concreta', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=26), 'Explicarle por qué no fue tu culpa', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=26), 'Decirle que no se puede hacer nada', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=26), 'Evitar la conversación', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Debes elegir entre cerrar una tarea rápido o hacerlo bien para el cliente. ¿Qué opción es más y menos efectiva?', 'sjt', 27);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=27), 'Orientación al cliente');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=27), 'Tomarte el tiempo necesario para hacerlo bien e informar el nuevo plazo', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=27), 'Entregarlo rápido aunque quede incompleto', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=27), 'Entregarlo tarde sin avisar', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=27), 'Delegar la tarea sin seguimiento', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Se presenta una falla inesperada en un proceso clave. ¿Qué opción es más y menos efectiva?', 'sjt', 28);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=28), 'Resolución de problemas');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=28), 'Analizar la causa raíz y proponer una solución estructurada', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=28), 'Aplicar una solución rápida sin analizar la causa', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=28), 'Esperar que alguien más lo resuelva', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=28), 'Ignorar la falla si no te afecta directamente', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Tienes información incompleta para tomar una decisión importante. ¿Qué opción es más y menos efectiva?', 'sjt', 29);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=29), 'Resolución de problemas');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=29), 'Buscar activamente la información faltante antes de decidir', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=29), 'Decidir con lo que tienes sin buscar más información', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=29), 'Postergar la decisión indefinidamente', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=29), 'Decidir al azar', 0, 4);
INSERT INTO evaluacion_preguntas (evaluacion_id, enunciado, tipo_pregunta, orden) VALUES (4, 'Dos soluciones posibles a un problema tienen pros y contras distintos. ¿Qué opción es más y menos efectiva?', 'sjt', 30);
INSERT INTO evaluacion_competencias (pregunta_id, competencia_nombre) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=30), 'Resolución de problemas');
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=30), 'Evaluar ambas con criterios claros antes de decidir', 3, 1);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=30), 'Elegir la primera que se te ocurre', 1, 2);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=30), 'Pedir que alguien más decida por ti', 0, 3);
INSERT INTO evaluacion_opciones (pregunta_id, texto, puntaje, orden) VALUES ((SELECT id FROM evaluacion_preguntas WHERE evaluacion_id=4 AND orden=30), 'Combinar ambas sin analizar si es viable', 0, 4);
